# yavzan/comfyui:latest taban imajını kullan
FROM yavzan/comfyui-flux:models AS base

ARG HUGGINGFACE_ACCESS_TOKEN
ARG WORKDIR

# Çalışma dizini
WORKDIR ${WORKDIR}/ComfyUI

# `test_input.json` dosyasını doğru konuma kopyala
# COPY src/* .
# COPY main.ipynb .
# # COPY test_input.json .

EXPOSE 8188 8888

CMD ["bash", "./start.sh"]
