FROM yavzan/comfyui-image2image:base AS base

ARG HUGGINGFACE_ACCESS_TOKEN
ARG WORKDIR
# Çalışma dizini
WORKDIR ${WORKDIR}/ComfyUI

RUN git -C ./custom_nodes clone --depth 1 https://github.com/ltdrdata/ComfyUI-Manager.git && \
    git -C ./custom_nodes clone --depth 1 https://github.com/mav-rik/facerestore_cf.git && \
    git -C ./custom_nodes clone --depth 1 https://github.com/kijai/ComfyUI-MochiWrapper.git && \
    git -C ./custom_nodes clone --depth 1 https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite.git && \
    git -C ./custom_nodes clone --depth 1 https://github.com/kijai/ComfyUI-KJNodes.git && \
    git -C ./custom_nodes clone --depth 1 https://github.com/kijai/ComfyUI-SUPIR.git && \
    git -C ./custom_nodes clone --depth 1 https://github.com/cubiq/ComfyUI_essentials && \
    git -C ./custom_nodes clone --depth 1 https://github.com/rgthree/rgthree-comfy.git

RUN chmod +x ./install-nodes-dependencies.sh
RUN --mount=type=cache,target=/root/.cache/pip \
    ./install-nodes-dependencies.sh
