services:
  base:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: python:3.11-slim
        COMFYUI_SHA: e7d47827364e628f1e89c7392ec00f9b78f6bca6
        PYTORCH_VERSION: 2.4.0
        WORKDIR: /workspace
    image: yavzan/comfyui-image2image:base
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    ports:
      - 8188:8188
      - 8888:8888
    networks:
      - comfyui_network

  models:
    build:
      context: .
      dockerfile: Dockerfile.Models
      args:
        HUGGINGFACE_ACCESS_TOKEN: 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
        WORKDIR: /workspace
    image: yavzan/comfyui-image2image:models
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - HUGGINGFACE_ACCESS_TOKEN=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
    volumes:
      - ./models:/workspace/ComfyUI/models
    command: bash ./start.sh
    ports:
      - 8189:8188
      - 8889:8888
    networks:
      - comfyui_network

  models2:
    build:
      context: .
      dockerfile: Dockerfile.Models2
      args:
        HUGGINGFACE_ACCESS_TOKEN: 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
        WORKDIR: /workspace
    image: yavzan/comfyui-image2image:models2
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - HUGGINGFACE_ACCESS_TOKEN=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
    volumes:
      - ./models:/workspace/ComfyUI/models
    command: bash ./start.sh
    ports:
      - 8190:8188
      - 8890:8888
    networks:
      - comfyui_network

  add:
    build:
      context: .
      dockerfile: Dockerfile.Add
      args:
        HUGGINGFACE_ACCESS_TOKEN: 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
        WORKDIR: /workspace
    image: yavzan/comfyui-image2image:add
    volumes:
      - ./output:/workspace/ComfyUI/output
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - 8191:8188
      - 8891:8888
    environment:
      - HUGGINGFACE_ACCESS_TOKEN=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
    command: bash ./start.sh
    networks:
      - comfyui_network

  nodes:
    build:
      context: .
      dockerfile: Dockerfile.Nodes
      args:
        HUGGINGFACE_ACCESS_TOKEN: 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
        WORKDIR: /workspace
    image: yavzan/comfyui-image2image:nodes
    environment:
      - HUGGINGFACE_ACCESS_TOKEN=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
    ports:
      - 8192:8188
      - 8892:8888
    networks:
      - comfyui_network

networks:
  comfyui_network:
    driver: bridge
